### ISSUE TITLE
Forecasting signatures

### ISSUE THREAD

**Issue by wmay** [ProjectPetition/Project-Petition-Web-App#11]
I've got some decent-looking forecasts working. Now we just need to get it on the website.

We don't want the server to have to run this while it's creating the page (it's a tad slow), so I think the best approach would be to have a 'petition' model that holds the forecast information. Then we can update that every night.

The forecast relies on the # of signatures added each day, so we have to get that info somehow. Maybe we can just add that to the petition model, and update that nightly as well.

I already have most of the code we need to update the info lying around in various scripts, so if we can get R installed then I could just update the website database directly from R every night. Or else we can translate the code into whatever the web app is using.

I haven't tried chart.js before. I know it's pretty easy to show a time series with confidence intervals in MetricsGraphics.js, if that helps.
http://metricsgraphicsjs.org/examples.htm
Here's an example:
http://willonrails.com/top_libertarians/112

Forecasts for a few different petitions, made on day 10:
![forecasts](https://cloud.githubusercontent.com/assets/4205859/9977948/3a603a20-5ee8-11e5-9f52-c8be401c60a6.png)

How the forecast changes over time for 1 petition:
![forecasts2](https://cloud.githubusercontent.com/assets/4205859/9977954/7f21b238-5ee8-11e5-9725-6a1d9766fd35.png)

**Comment by wmay** [comment]
@UAhmad7 are we using a Javascript framework for the backend of the website? I'm mildly Javascript-phobic, so if we are then I'm mostly depending on you to set up the 'petition' model for this. Otherwise I'd be happy to take a shot at it.

Just for the basic graph, the model would need to have the attributes
- created date
- signature counts for days 1-30
- signature forecasts for days 1-30
- low-end forecasts days 1-30
- high-end forecasts days 1-30

and then whatever else we want to show on the pages for individual petitions (probably title, body, category).

**Comment by UAhmad7** [comment]
We are going to be using PHP mostly for the backend. I will create the model for this if you like. I will ask the server admin to add support for R as well. I will let you know as soon as the server is ready. I started with Chart.js but I think it would be better to use some other library to develop the graphs. These graphs look very nice. Let's meet up to discuss our plans further for this project. I will email everyone.

**Comment by wmay** [comment]
Yeah, my PHP is pretty weak too.

I wonder if we should use WordPress in that case, on the assumption that sooner or later someone will want to post some summaries of research or news about the project. But I guess we can ask about that at the meeting on Friday.

We would need to have the `r-base-core` and `r-base-dev` libraries installed on the server (or the equivalent for their OS) to run the R script.

**Comment by UAhmad7** [comment]
I have never used R in the back-end. Do you know how to serve data using R to a web page?

**Comment by wmay** [comment]
Yeah, but I'm not going to try that here (it's not fun, and we'd have to set up another server).

If you have a website database containing the petition info, I can write to it directly from R. You might have to add some code in your PHP to make sure the website gets the new info from the database instead of pulling it from an outdated cache. Other than that I don't think it'll change anything on your end. That's the simplest way I know how to do this, outside of rewriting the forecasting code in PHP.
